sudo: required

env:
  global:
    - CGO_ENABLED: 1
matrix:
  include:
    - os: linux
      dist: xenial
      env: TYPE=mono
      language: go
    - os: linux
      dist: xenial
      env: TYPE=dotnet
      language: go
    - os: osx
      language: csharp
      oxs_image: xcode8
      solution: lib/swig/LibSkycoinNet.sln
      env: TYPE=mono
      mono: 5.18.1
      dotnet: 2.2.401
    - os: osx
      language: csharp
      oxs_image: xcode8
      solution: lib/swig/LibSkycoinDotNet.sln
      env: TYPE=dotnet
      mono: 5.18.1
      dotnet: 2.2.401

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash .travis/install_linux.sh ; fi
  - ./.travis/install-deps.sh
  - ./.travis/install-travis-gcc.sh
  - eval "CC=gcc && CXX=g++"
  - go get github.com/gz-c/gox
  - go get github.com/skycoin/skycoin

install:
  - eval "$(gimme 1.11)"
  
script:
  - (nohup make -C ~GOPATH/src/github.com/skycoin/skycoin run-daemon ARGS="-db-read-only=true -disable-csrf=false -disable-networking=true -enable-all-api-sets=true -download-peerlist=false -db-path=$GOPATH/src/github.com/skycoin/skycoin/src/api/integration/testdata/blockchain-180.db" &)
  - make test-libsky-$TYPE
  - make test-skyapi
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./.travis/deploy.sh && ./.travis/deploy.sh
  on:
    tags: true
    repo: simelo/libskycoin_dotnet
